config/routes.rb
Rails.application.routes.draw do
  
 root 'pages#landing_page'
 get '/o_nama' => 'pages#o_nama'
 get '/novosti' => 'pages#novosti'
 get '/kontakt' => 'pages#kontakt'

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def landing_page

end   


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<section id="footer">
    <div class="container">
        <div class="row text-center text-xs-center text-sm-left text-md-left">
            <div class="col-xs-12 col-sm-4 col-md-4">
                <h5>Korisni linkovi</h5>
                <ul class="list-unstyled quick-links">
                    <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Početna</a></li>
                    <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>O nama</a></li>
                    <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Novosti</a></li>
                    <li><a href="javascript:void();"><i class="fa fa-angle-double-right"></i>Kontakt</a></li>
                   
                </ul>
            </div>
            
            
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
                <ul class="list-unstyled list-inline social text-center">
                    <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-facebook"></i></a></li>
                    <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-twitter"></i></a></li>
                    <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-instagram"></i></a></li>
                    <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-google-plus"></i></a></li>
                    <li class="list-inline-item"><a href="javascript:void();" target="_blank"><i class="fa fa-envelope"></i></a></li>
                </ul>
            </div>
            </hr>
        </div>	
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                <p>Srednja ekonomska škola Sarajevo</p>
                <p class="h6">&copy Sva prava zadržana. Zabranjeno preuzimanje sadržaja bez dozvole izdavača.<a class="text-green ml-2" </p>
            </div>
            </hr>
        </div>	
    </div>
</section>
<!-- ./Footer -->







<style>

/* Footer */
@import url('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css');
section {
    padding: 60px 0;
}

section .section-title {
    text-align: center;
    color: #007b5e;
    margin-bottom: 50px;
    text-transform: uppercase;
}
#footer {
    background: #007b5e !important;
}
#footer h5{
	padding-left: 10px;
    border-left: 3px solid #eeeeee;
    padding-bottom: 6px;
    margin-bottom: 20px;
    color:#ffffff;
}
#footer a {
    color: #ffffff;
    text-decoration: none !important;
    background-color: transparent;
    -webkit-text-decoration-skip: objects;
}
#footer ul.social li{
	padding: 3px 0;
}
#footer ul.social li a i {
    margin-right: 5px;
	font-size:25px;
	-webkit-transition: .5s all ease;
	-moz-transition: .5s all ease;
	transition: .5s all ease;
}
#footer ul.social li:hover a i {
	font-size:30px;
	margin-top:-10px;
}
#footer ul.social li a,
#footer ul.quick-links li a{
	color:#ffffff;
}
#footer ul.social li a:hover{
	color:#eeeeee;
}
#footer ul.quick-links li{
	padding: 3px 0;
	-webkit-transition: .5s all ease;
	-moz-transition: .5s all ease;
	transition: .5s all ease;
}
#footer ul.quick-links li:hover{
	padding: 3px 0;
	margin-left:5px;
	font-weight:700;
}
#footer ul.quick-links li a i{
	margin-right: 5px;
}
#footer ul.quick-links li:hover a i {
    font-weight: 700;
}

@media (max-width:767px){
	#footer h5 {
    padding-left: 0;
    border-left: transparent;
    padding-bottom: 0px;
    margin-bottom: 10px;
}
}

</style>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
  <a href="<%= root_path %>"><img src ="logo.png" width="120"></a>
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Početna <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= o_nama_path %>">O nama </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= novosti_path %>">Novosti </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= kontakt_path %>">Kontakt</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prijavaefsa</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  
</head>

  <body style="background-color:lightgray;">

<%= render 'layouts/navbar' %>

  <div class="container" >
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>


<style>
p{
    text-align: justify;
}
</style>


  </body>
</html>

app/views/pages/kontakt.html.erb
<br/><br/><br/>
	<div class="row-fluid">
        <div class="span8">
        	<iframe width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2877.1040801887802!2d18.39013531550428!3d43.853671379115056!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4758c91870ce352f%3A0x7b98c3ca162fc44c!2sSrednja+ekonomska+%C5%A1kola!5e0!3m2!1sbs!2sba!4v1525783755821" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe></iframe>
    	</div>
    	
      	<div class="span4">
    		<h2>Kontakt</h2>
    		<address>
            <strong>Srednja ekonomska škola</strong><br>
    			Zmaja od Bosne 39<br>
    			71000<br>
    			Sarajevo<br>
    			Bosna i Hercegovina<br>
                <br>
                <abbr title="Mail">E-Mail:</abbr> ekoskola@hotmail.com
                <br/>
    			<abbr title="Telefon">Tel:</abbr> +387 33 724 611
    		</address>
    	</div>
    </div>

	<br/><br/><br/><br/><br/><br/><br/>

app/views/pages/landing_page.html.erb
<br/><br/>
<div class="w3-content w3-display-container">
<img class="mySlides" src="/slika11.jpg" style="width:1000px; height:600px;">
<img class="mySlides" src="/slika12.jpg" style="width:1000px; height:600px;">
<img class="mySlides" src="/slika13.jpg" style="width:1000px; height:600px;">
<img class="mySlides" src="/slika14.jpg" style="width:1000px; height:600px;">

<button class="w3-button w3-black w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
<button class="w3-button w3-black w3-display-right" onclick="plusDivs(1)">&#10095;</button>
</div>

<script>
var slideIndex = 1;
showDivs(slideIndex);

function plusDivs(n) {
showDivs(slideIndex += n);
}

function showDivs(n) {
var i;
var x = document.getElementsByClassName("mySlides");
if (n > x.length) {slideIndex = 1}    
if (n < 1) {slideIndex = x.length}
for (i = 0; i < x.length; i++) {
   x[i].style.display = "none";  
}
x[slideIndex-1].style.display = "block";  
}
</script>





<br/><br/>


<div class="row">
    <div class="col-md-12"> 

    </div> 
</div> 

<div class="jumbotron">
    <div class="row">

        <div class="col-md-4">
        <h3> Historijat </h3>

        <p> Kraj 19. i početak 20 stoljeća u Bosni i Hercegovini su obilježeni vidnim promjenama privrednih prilika. Bosna i Hercegovina se postepeno, od izrazito agrarne i manufakturne zemlje pretvara u zemlju u kojoj se zanatstvo, trgovina i industrija naglo razvijaju. Taj razvoj pratio je i razvoj bankarstva, privrednih komora (trgovačke, zanatske) kao i sve veća potreba za stručnim kadrom u novoj privredi. U početku je stručni finansijski kadar dolazio iz drugih krajeva Austrougarske, ali ubrzo se pojavila ideja o obrazovanju domaćeg stručnog finansijskog kadra. Nosilac te ideje bile su privredne komore - konkretno Trgovačko - obrtnička komora, koja je zagovarala ideju školovanja domaćeg kadra. </p>
        <span><a href="<%= o_nama_path %>"> Nastavite čitati na narednoj stranici...</a></span>
        </div>

        <div class="col-md-4">
        <h3> Novosti </h3>

        <p> Učenici trećeg razreda naše škole odrekli su se ovogodišnjeg proljetnog izleta sa razrednicima u korist oboljelog prijatelja iz III-6 odjeljenja. 

        Nakon humanitarnog bazara 26. aprila i sveopće humanitarne akcije, sredstva koja bi bila utrošena za organizaciju izleta uplatili su na njegov račun, a oni se 27. aprila našli sa razrednicima u Vilsonovom šetalištu, gdje su prošetali zajedno, družili se ili popili kafu u jednom od kafića. Akcija za svaku pohvalu!  </p>
        <span><a href="<%= novosti_path %>"> Nastavite čitati na narednoj stranici...</a></span>
        </div>

        <div class="col-md-4">
        <h3> Nastava </h3>

        <p>Tokom dugog postojanja škola je mijenjala i primjenjivala više nastavnih planova i programa. Glavne izmjene u nastavnim planovima i programima bile su u nacionalnim predmetima: jeziku, historiji i geografiji. Što se tiče stručnih predmeta nije bilo većih izmjena i uglavnom je primjenjivan nastavni plan i program iz 1938. godine.
        Pored klasičnog pristupa obradi lekcija iz udžbenika i knjiga, sveprisutna je multimedijalna nastava koja odgovara modernim pedagoškim mjerilima. Također, dvije sedmice (jedna u prvom i jedna u drugom polugodištu) nastave se realiziraju na principu učenja na daljinu, putem interneta. </p>
        </div>

    </div>
</div>

 <hr/> 

<div class="jumbotron">
    <div class="row">

        <div class="col-md-8">
            <h3>Djelatnici u nastavi  </h3>
        </div>

    </div>

<br/><br/>

    <div class="row">

        <div class="col-md-3">
            <img src="profilna3.jpg"  height="150" width="150" >   
        </div>

        <div class="col-md-3">
            <img src="profilna2.png"  height="150" width="150" >   
        </div>

        <div class="col-md-3">
            <img src="profilna3.jpg"  height="150" width="150" >       
        </div>

        <div class="col-md-3">
            <img src="profilna2.png"  height="150" width="150" >    
        </div>

    </div>
</div>


    <hr/> 

<div class="jumbotron">
    <div class="row">

        <div class="col-md-8">
            <h3>Učenici </h3>
        </div>

    </div>

<br/><br/>


    <div class="row">

        <div class="col-md-3">
            <img src="profilna3.jpg"  height="150" width="150" >   
        </div>

        <div class="col-md-3">
            <img src="profilna2.png"  height="150" width="150" >   
        </div>

        <div class="col-md-3">
            <img src="profilna3.jpg"  height="150" width="150" >      
        </div>

        <div class="col-md-3">
            <img src="profilna2.png"  height="150" width="150" >    
        </div>

    </div>
</div>





<style>

span a{
    color: lightblue;
    text-decoration: none;
}
span a:hover{
    color: blue;
    text-decoration: none;
}


</style>

app/views/pages/novosti.html.erb
<div class="row">
    <div class="col-md-12"> 
        <center>
             <img src="slika2.jpg"  height="500" width="1024" >
        </center>
    </div> 
</div>

<br/>

<div class="jumbotron">

    <div class="row">
        <div class="col-md-12"> 
            <h3> <img class="kockice" src="/redsquare.png" />  Izdvojeno </h3>
            <hr/>
        </div>
    </div>

    <div class="row">

        <div class="col-md-3">
                <span> Dani hemije </span><br/>
                
                <img src="http://www.ses.edu.ba/_/rsrc/1526025187220/home/hemija2.jpg?" style='width:100%; height:auto;' />
                
                <h3> Otvoreni dani hemije na PMF-u u Sarajevu </h3>
                <p> Učenici I (prvog) razreda naše Škole pokazali su svoj interes za hemijom, prisustvom na manifestaciji „OTVORENI DANI HEMIJE“ na Prirodno matematičkom fakultetu u Sarajevu, 19. aprila 2018. godine.  </p>
                <span> 14-Maj-2018 </span>
        </div>

        <div class="col-md-6">
                <span> Dan otvorenih vrata </span><br/>
                <img src="http://www.ses.edu.ba/_/rsrc/1525352354481/home/setnja_za_prijatelja.jpg?" style='width:100%; height:auto;' />
                <h3> Dan otvorenih vrata u ekonomskoj školi </h3>
                <p> 17.4.2018. godine učenici II-1 i II-2 razreda su posjetili tvornicu Coca-Cole u Hadžićima, Sarajevo i upoznali organizacione, marketinške, tehnološke aspekte poslovanja ove moderne punionice koja proizvodi i prodaje najpopularnije i najprodavanije piće u historiji i najpoznatiji svjetski brend. </p>
                <span> 14-Maj-2018 </span>
        </div>

        <div class="col-md-3">
                <span> Posjeta Coca-Coli </span><br/>
                <img src="http://www.ses.edu.ba/_/rsrc/1524234204416/home/cc1.jpg?" style='width:100%; height:40%;' />
                <h3> Učenici posjetili punionicu Coca-Cole u Hadžićima </h3>
                <p> Nakon humanitarnog bazara 26. aprila i sveopće humanitarne akcije. Akcija za svaku pohvalu! </p>
                <span> 14-Maj-2018 </span>
        </div>

    </div>
</div>
    <br/> <br/> <br/>


<div class="jumbotron"> 

    <div class="row">
        <div class="col-md-12"> 
            <h3> <img class="kockice" src="/bluesquare.png" />   Ostale novosti </h3>
            <hr/>
        </div>
    </div> 

    <div class="row">

        <div class="col-md-3">
                <span> Općinsko takmičenje </span><br/>
                <img src="http://www.ses.edu.ba/_/rsrc/1524148607080/home/XXIII%20OTPP%2020.jpg?" style='width:100%; height:auto;' />
                <h3> Drugo mjesto na općinskom takmičenju iz pružanja prve pomoći </h3>
                <p> U subotu 24. marta 2018. godine u prostorijama JU OŠ “Kovačići”, u organizaciji Crvenog križa Općine Novo Sarajevo. održano je XXIII općinsko takmičenje iz pružanja prve pomoći osnovnih i srednjih škola sa područja općine Novo Sarajevo.  </p>
                <span> 14-Maj-2018 </span>
        </div>

        <div class="col-md-3">
                <span> Ekonomijada 2018. </span><br/>
                <img src="http://www.ses.edu.ba/_/rsrc/1523433445794/home/ekonomijada181.jpg?" style='width:100%; height:auto;' />
                <h3> Drugo mjesto na Ekonomijadi 2018. godine </h3>
                <p> Srednja ekonomska škola, Sarajevo učestvovala je na ovogodišnjoj "Ekonomijadi", trodnevnom druženju i razmjenjivanju znanja i iskustva iz ekonomske grupe predmeta kojem je domaćin bila Prva ekonomska škola Zagreb. </p>
                <span> 14-Maj-2018 </span>
        </div>

        <div class="col-md-3">
                <span> Narodno pozorište </span><br/>
                <img src="http://www.ses.edu.ba/_/rsrc/1522835533402/home/nps1.jpg?" style='width:100%; height:auto;' />
                <h3> Posjeta Narodnom pozorištu </h3>
                <p> NMjesec mart u našoj školi ove godine bio je posvećen pozorišnoj umjetnosti. U organizaciji Škole, a finansirana sredstvima učeničke školarine, u dva termina organizirana je posjeta učenika Škole Narodnom pozorištu, Sarajevo. </p>
                <span> 14-Maj-2018 </span>
        </div>

        <div class="col-md-3">
            <span> Karate turnir </span><br/>
            <img src="http://www.ses.edu.ba/_/rsrc/1525352354481/home/setnja_za_prijatelja.jpg?" style='width:100%; height:auto;' />
            <h3> Sportski uspjeh našeg učenika </h3>
            <p> Nakon humanitarnog bazara 26. aprila i sveopće humanitarne akcije, sredstva koja bi bila utrošena za organizaciju izleta uplatili su na njegov račun, a oni se 27. aprila našli sa razrednicima u Vilsonovom šetalištu, gdje su prošetali zajedno, družili se ili popili kafu u jednom od kafića. </p>
            <span> 14-Maj-2018 </span>
        </div>

    </div>
<br/><br/>
    <div class="row">

        <div class="col-md-3">
                <span> Poklon dječijem domu Bjelave </span><br/>
                <img src="http://www.ses.edu.ba/_/rsrc/1520698008345/home/domb.jpg?" style='width:100%; height:auto;' />
                <h3> Poklon dječijem domu Bjelave </h3>
                <p> Učenice naše škole uručile su 8.3.2017. godine usisivač Dječijem domu Bjelave. 

                Usisivač je kupljen od novca koji su učesnici projekta Volontiraj kreditiraj osvojili na Sajmu kreditiranja projektom pod nazivom Djeca su ukras svijeta.  </p>
                <span> 14-Maj-2018 </span>
        </div>

        <div class="col-md-6">
                <span> Promotivni video </span><br/>
                <iframe width="500" height="315" src="https://www.youtube.com/embed/NlvmZY5lCnc" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                <h3> Zašto je moja škola COOL? </h3>
                <p> Nakon humanitarnog bazara 26. aprila i sveopće humanitarne akcije, sredstva koja bi bila utrošena za organizaciju izleta uplatili su na njegov račun, a oni se 27. aprila našli sa razrednicima u Vilsonovom šetalištu, gdje su prošetali zajedno, družili se ili popili kafu u jednom od kafića. Akcija za svaku pohvalu! </p>
                <span> 14-Maj-2018 </span>
        </div>

        <div class="col-md-3">
                <span> Mini naslov </span><br/>
                <img src="http://www.ses.edu.ba/_/rsrc/1525352354481/home/setnja_za_prijatelja.jpg?" style='width:100%; height:auto;' />
                <h3> Veliki naslov </h3>
                <p> Nakon humanitarnog bazara 26. aprila i sveopće humanitarne akcije, sredstva koja bi bila utrošena za organizaciju izleta uplatili su na njegov račun, a oni se 27. aprila našli sa razrednicima u Vilsonovom šetalištu, gdje su prošetali zajedno, družili se ili popili kafu u jednom od kafića. Akcija za svaku pohvalu! </p>
                <span> 14-Maj-2018 </span>
        </div>

    </div>
    <br/><br/><br/>
    <div class="row">

        <div class="col-md-3">
                <span> Mini naslov </span><br/>
                <img src="http://www.ses.edu.ba/_/rsrc/1525352354481/home/setnja_za_prijatelja.jpg?" style='width:100%; height:auto;' />
                <h3> Veliki naslov </h3>
                <p> Nakon humanitarnog bazara 26. aprila i sveopće humanitarne akcije, sredstva koja bi bila utrošena za organizaciju izleta uplatili su na njegov račun, a oni se 27. aprila našli sa razrednicima u Vilsonovom šetalištu, gdje su prošetali zajedno, družili se ili popili kafu u jednom od kafića. Akcija za svaku pohvalu! </p>
                <span> 14-Maj-2018 </span>
        </div>

        <div class="col-md-3">
                <span> Mini naslov </span><br/>
                <img src="http://www.ses.edu.ba/_/rsrc/1525352354481/home/setnja_za_prijatelja.jpg?" style='width:100%; height:auto;' />
                <h3> Veliki naslov </h3>
                <p> Nakon humanitarnog bazara 26. aprila i sveopće humanitarne akcije, sredstva koja bi bila utrošena za organizaciju izleta uplatili su na njegov račun, a oni se 27. aprila našli sa razrednicima u Vilsonovom šetalištu, gdje su prošetali zajedno, družili se ili popili kafu u jednom od kafića. Akcija za svaku pohvalu! </p>
                <span> 14-Maj-2018 </span>
        </div>

        <div class="col-md-3">
                <span> Mini naslov </span><br/>
                <img src="http://www.ses.edu.ba/_/rsrc/1525352354481/home/setnja_za_prijatelja.jpg?" style='width:100%; height:auto;' />
                <h3> Veliki naslov </h3>
                <p> Nakon humanitarnog bazara 26. aprila i sveopće humanitarne akcije, sredstva koja bi bila utrošena za organizaciju izleta uplatili su na njegov račun, a oni se 27. aprila našli sa razrednicima u Vilsonovom šetalištu, gdje su prošetali zajedno, družili se ili popili kafu u jednom od kafića. Akcija za svaku pohvalu! </p>
                <span> 14-Maj-2018 </span>
        </div>

        <div class="col-md-3">
            <span> Mini naslov </span><br/>
            <img src="http://www.ses.edu.ba/_/rsrc/1525352354481/home/setnja_za_prijatelja.jpg?" style='width:100%; height:auto;' />
            <h3> Veliki naslov </h3>
            <p> Nakon humanitarnog bazara 26. aprila i sveopće humanitarne akcije, sredstva koja bi bila utrošena za organizaciju izleta uplatili su na njegov račun, a oni se 27. aprila našli sa razrednicima u Vilsonovom šetalištu, gdje su prošetali zajedno, družili se ili popili kafu u jednom od kafića. Akcija za svaku pohvalu! </p>
            <span> 14-Maj-2018 </span>
        </div>

    </div>
</div>




<style>
span{
    color: darkred;
    font-variant: small-caps;
}
.kockice{
    width: 15px;
    height: 15px;
}

</style>

app/views/pages/o_nama.html.erb
<div class="row">
    <div class="col-md-12"> 
        <center>
        <img src="slika2.jpg"  height="500" width="1024" >
        </center><br/>
    </div> 
</div> 

<div class="jumbotron">

    <div class="row">

        <div class="col-md-12">
            <h3> Historijat </h3>

            <p> Kraj 19. i početak 20 stoljeća u Bosni i Hercegovini su obilježeni vidnim promjenama privrednih prilika. Bosna i Hercegovina se postepeno, od izrazito agrarne i manufakturne zemlje pretvara u zemlju u kojoj se zanatstvo, trgovina i industrija naglo razvijaju. Taj razvoj pratio je i razvoj bankarstva, privrednih komora (trgovačke, zanatske) kao i sve veća potreba za stručnim kadrom u novoj privredi. U početku je stručni finansijski kadar dolazio iz drugih krajeva Austrougarske, ali ubrzo se pojavila ideja o obrazovanju domaćeg stručnog finansijskog kadra. Nosilac te ideje bile su privredne komore - konkretno Trgovačko - obrtnička komora, koja je zagovarala ideju školovanja domaćeg kadra. Prvo su kao stručne škole toga smjera u Bosni i Hercegovini otvorene trgovačke škole. Prva trgovačka skola osnovana je 1885. godine u Tuzli i imala je tri razreda. Poslije Tuzle, trgovačke škole su otvorene u Brčkom, Banjoj Luci, Mostaru, Livnu, Sarajevo, Bihaću, Bijeljini, Travniku i Trebinju. Ove škole su radile do 1908. godine kada ih je ukinula Zemaljska vlada za Bosnu i Hercegovinu, jer nisu zadovoljavale kriterij trgovačkih skola. Iste godine otvorene su nove trgovačke stručne škole u Sarajevu, Mostaru i Tuzli i trajale su pet godina.

                Rasprava o otvaranju finansijske škole višeg stupnja vodila se nekoliko godina. Tako već 1910. godine Trgovačka škola i obrtnička komora za BiH u Sarajevu u svom dopisu od 19.11.1910. godine upućenom Zemaljskoj vladi za BiH traži otvaranje jednogodišnjeg merkatilnog tečaja za apsolvente srednjih škola i ujedno predlaže da se u Sarajevu osnuje Trgovačka akademija ''sa sličnim uređenjem i nastavnom osnovom kao akademije u Monarhiji''. Ta ideja dalje je razrađena u Trgovačkoj i obrtničkoj komori pa je na njenoj plenarnoj sjednici 19. i 20. juna 1911. godine pod tačkom 5. dato detaljno obrazloženje o potrebi otvaranja Trgovačke akademije u Sarajevu. Kao rezultati aktivnosti u oktobru 1912. godine u Sarajevu je otvorena Trgovačka akademija.
                
                Svečano otvaranje Državne trgovačke akademije u Sarajevu bilo je 1. oktobra 1912. godine u 10 sati u auli Velike realke Franje Josipa u Sarajevu. Akademiju je otvorio izaslanik Zemaljske vlade za Bosnu i Hercegovinu vladin savjetnik Franjo Bordnik. Svoj rad Akademija je odmah započela na osnovu statuta o uređenju Državne trgovačke akademije u Sarajevu u kome je detaljno bio obrađen rad te škole. Na osnovu statuta školovanje je trajalo 4 godine, a vrijedile su sve odredbe kao i za druge srednje škole u BiH. U prvoj 1912/1913. školskoj godini otvoren je samo prvi razred, sljedećih godina otvarali su se i ostali razredi tako da je 1915/16. godine Akademija imala IV razred, odnosno, te godine maturiralo je prvih osam učenika Državne trgovačke akademije u Sarajevu. Ovako mali broj prvih maturanata, u odnosu na 128 učenika upisanih u prvi razred 1912/13. godine, bio je uslovljen Prvim svjetskim ratom, jer su mnogi učenici ili napustili školu ili bili mobilisani u vojsku. </p>

        </div>
    </div>
</div>

<hr/>

<div class="jumbotron">

    <div class="row">
        <div class="col-md-3">
        <img src="slika3.jpg"  height="150" width="200" >

        </div>

        <div class="col-md-3">
        <img src="slika4.jpg"  height="150" width="200" >   
        </div>

        <div class="col-md-3">
        <img src="slika5.jpg"  height="150" width="200" >   
            
        </div>

        <div class="col-md-3">
        <img src="slika6.jpg"  height="150" width="200" >   
        </div>
    </div>
    
</div>